services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      CLIENT_URL: http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
